((nil . ((indent-tabs-mode . nil)
         (fill-column . 70)
         (sentence-end-double-space . t)))
 (org-mode . ((mode . auto-fill)
              (eval . (org-hugo-auto-export-mode))))
 (markdown-mode . ((mode . auto-fill))))
