((nil . ((indent-tabs-mode . nil)
         (fill-column . 70)
         (sentence-end-double-space . t)))
 (org-mode . ((mode . auto-fill)
              (org-hugo-auto-export-on-save . t)))
 (markdown-mode . ((mode . auto-fill))))
